apiVersion: microsoft.resources.azure.com/v1alpha1api20200601
kind: ResourceGroup
metadata:
  name: auto-cluster2
  namespace: default
spec:
  location: westus2
---
apiVersion: microsoft.containerservice.azure.com/v1alpha1api20210501
kind: ManagedCluster
metadata:
  name: auto-cluster2
  namespace: default
spec:
  location: westus2
  owner:
    name: auto-cluster2
  dnsPrefix: asonf
  agentPoolProfiles:
    - name: pool1
      count: 1
      vmSize: Standard_D2s_v4
      osType: Linux
      mode: System
  identity:
    type: SystemAssigned
