apiVersion: v1
kind: Service
metadata:
  name: python-service-pipeline
spec:
  selector:
    app: python-demo-cd
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
