apiVersion: v1
kind: Service
metadata:
  name: python-service-pipeline
  namespace: python-argo
spec:
  selector:
    app: python-demo-cd
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8001
