name: Container CI

on:
  push:
    branches: [ main ]
    paths: 
    - 2_container_ci/**
    - .github/workflows/CI-container.yaml

  workflow_dispatch:
  
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: az CLI login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: ACR login
        run: az acr login -n nfacr
         
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: 2_container_ci
          push: true
          tags: nfacr.azurecr.io/python-webapp/demo:${{ github.run_number }}
          
