name: Container CICD to kubernetes

on:
  push:
    branches: [ main ]
    paths: 
    - 4_container_ci-cd-kubernetes/**
    - .github/workflows/CICD-container-kubernetes.yaml

  workflow_dispatch:
  
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: az CLI login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: ACR login
        run: az acr login -n nfacr
         
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: 4_container_ci-cd-kubernetes
          push: true
          tags: nfacr.azurecr.io/python-webapp/cd-demo:${{ github.run_number }}
  CD:
    needs: CI
    runs-on: ubuntu-latest
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
          resource-group: rg-handsonaks
          cluster-name: handsonaks

      - name: Update deployment
        run: sed -i 's|nfacr.azurecr.io/python-webapp/cd-demo:.*|nfacr.azurecr.io/python-webapp/cd-demo:${{ github.run_number }}|gi' 4_container_ci-cd-kubernetes/deployment.yaml

      - name: Update files
        run: kubectl apply -f 4_container_ci-cd-kubernetes/
        
      - name: Wait for deployment to finish
        run: kubectl rollout status deployment python-deployment-pipeline
        
      - name: Get service IP
        run: |
          PUBLICIP=""
          while [ -z $PUBLICIP ]; do
            echo "Waiting for public IP..."
            PUBLICIP=$(kubectl get service python-service-pipeline -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
            [ -z "$PUBLICIP" ] && sleep 10
          done
          echo $PUBLICIP
